---
services:
  db:
    image: mariadb 
    container_name: db 
    command: --max-allowed-packet=64MB
    restart: always
    environment:
      - MARIADB_DATABASE=matomo
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    volumes:
      - db:/var/lib/mysql
    networks:
      - matomo

  matomo:
    image: matomo
    container_name: matomo
    restart: always
    depends_on:
      - db
    volumes:
      - matomo:/var/www/html
    networks:
      - matomo
      - proxy
    environment:
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${EMAIL}
      - VIRTUAL_HOST=${DOMAIN}

networks:
  matomo:
  proxy:
    external: true
    external: true
    name: http-proxy_proxy

volumes:
  matomo:
  db:
